### ISSUE TITLE
Change node for modify config

### ISSUE THREAD

**Issue by clubpi** [RonB/node-red-contrib-hydrawise#1]
Hi,

can i change the properties of the Hydrawise node with a function node?

msg.device =
{
    "coammand" : "on",
    "zone" : 1,
    "duration" : 100
}
return msg;

**Comment by RonB** [comment]
Hi,

Thank you for your request. Currently it's not possible but I am working on a next release and will provide the possibility to send command details via the message payload. Stay tuned for the next release.

Regards Ronald

**Comment by RonB** [comment]
Release 0.0.5 addresses your question. Please test this release by updating your node-red palette.
I also added an example to create a dynamic dashboard that can stop or run your zones. See the documentation of the command node and the readme.
