### ISSUE TITLE
Parameter with payload

### ISSUE THREAD

**Issue by m4tze-smart** [RonB/node-red-contrib-hydrawise#2]
**I'm submitting a ...**  (check one with "x")

### Problem
 - ( ) bug report => please search github for a similar issue or PR before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 - simplify the programming

 **Current behavior**
 
the parameter Zone and Duration are fixed in each flow
 
 **Expected behavior**
 
easy automation with a variable duration time and Zone number via payload input

 **Minimal reproduction of the problem with instructions**
 
   1. 
   2. 
   3. 
   
 ## Feature
 - ( x ) feature request
 
 **What is the motivation / use case for changing the behavior?**
manage the parameter duration time and zone number with a payload input to steer it via Lovelace with button-cards and a input_select slider 
 
 
 ## Support
 - support request => **Please do not submit support requests here**
 - ( ) simple question => please visit the Wiki and Info tab by clicking on the node inside Node-RED before

## Your Environment
**Please tell us about your environment:**

  * ( ) I am using just the Node-RED package
        
  * controller :
    
    - ( ) macOS: v 
    - ( x ) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting hydrawise system:
   
     - Name   : Hunter 12 Pro HC
     - Version:
     - Vendor :
     - Link   : https://
     
    
* **node-red-contrib-hydrawise version:** ``

* **Node:** (min. 6.10.x)
   `node --version` =

**Comment by RonB** [comment]
Hi, 
I do not use Home assistant but this should not be a problem. Configure the Lovalace button so that is sends a payload with the command, the zone-number and the duration. I don't know on the HA side but maybe it is something like this?

>type: button
tap_action:
..action: call-service
..service: nodered.trigger
..service_data:
....entity_id: switch.zone_3
....payload: 
.......command: run
.......duration: 18000
.......zone: 3
name: Run zone 3 for 30 minutes 
entity: switch.lovelace_button 

Let me know if it doesn't work, otherwise please send me your flow and the name of the nodered homeassistant package you use. I will try to reproduce and adjust your flow.

Regards, Ronald

**Comment by m4tze-smart** [comment]
Hi Ronald,

starting and stopping a valve with a manual duration time works great. THX

I've one Slider for the duration time and for each valve an own input_select button.
With a join flow I send this 2 informations to  start the correct zone with the right duration time.
This join flow works also for stopping the right zone.

But a second input_select button with Start/Stop to Stop Alle zones doesn't work.

Failure:
msg : error
"TypeError: Cannot read properties of undefined (reading 'stopAllZones')"

Home-assistant: node-red-contrib-home-assistant-websocket

Flow:

`[{"id":"10ba0f4e1fc10011","type":"tab","label":"Flow 3","disabled":false,"info":"","env":[]},{"id":"a1e88b59830d036f","type":"hydrawise-command","z":"10ba0f4e1fc10011","name":"","controller":"01a770885c419e","zone":"1","command":"stopAllZones","duration":1800,"x":1620,"y":240,"wires":[["f31cc3d2467d4446"]]},{"id":"216d0baadd7b623b","type":"debug","z":"10ba0f4e1fc10011","name":"debug 15","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":900,"y":340,"wires":[]},{"id":"5889aa997f7cfcb9","type":"change","z":"10ba0f4e1fc10011","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":850,"y":240,"wires":[["1eb2436eab012580","a1e88b59830d036f"]]},{"id":"f8e25d5774306f3d","type":"change","z":"10ba0f4e1fc10011","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":850,"y":280,"wires":[["076b5545aec505a2","216d0baadd7b623b"]]},{"id":"1eb2436eab012580","type":"debug","z":"10ba0f4e1fc10011","name":"debug 16","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1220,"y":180,"wires":[]},{"id":"076b5545aec505a2","type":"api-call-service","z":"10ba0f4e1fc10011","name":"","server":"bffecd85.30ce3","version":5,"debugenabled":false,"domain":"input_boolean","service":"turn_off","areaId":[],"deviceId":[],"entityId":["input_boolean.beregnung_zone1","input_boolean.beregnung_zone2","input_boolean.beregnung_zone3","input_boolean.beregnung_zone4","input_boolean.beregnung_zone5","input_boolean.beregnung_zone6","input_boolean.beregnung_zone7","input_boolean.beregnung_zone8","input_boolean.beregnung_zone9"],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"Aus","valueType":"str"}],"queue":"all","x":1100,"y":280,"wires":[["5aa4fd25ed12ac34"]]},{"id":"2f4d0587c3c411ee","type":"server-state-changed","z":"10ba0f4e1fc10011","name":"Manueller Stop","server":"bffecd85.30ce3","version":4,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"input_select.irrigation_program","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"Stop","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":"0","forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":540,"y":240,"wires":[["f8e25d5774306f3d","5889aa997f7cfcb9","2f358f9ed06d808a"],[]]},{"id":"5aa4fd25ed12ac34","type":"debug","z":"10ba0f4e1fc10011","name":"debug 17","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1360,"y":280,"wires":[]},{"id":"2f358f9ed06d808a","type":"change","z":"10ba0f4e1fc10011","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":850,"y":380,"wires":[["2990bb6f5454b211"]]},{"id":"20a4d6efa9b7f213","type":"api-call-service","z":"10ba0f4e1fc10011","name":"","server":"bffecd85.30ce3","version":5,"debugenabled":false,"domain":"input_select","service":"select_first","areaId":[],"deviceId":[],"entityId":["input_select.irrigation_program"],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"Start","valueType":"str"}],"queue":"all","x":1110,"y":440,"wires":[["ed1da33977f784f6"]]},{"id":"ed1da33977f784f6","type":"debug","z":"10ba0f4e1fc10011","name":"debug 18","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1360,"y":440,"wires":[]},{"id":"2990bb6f5454b211","type":"delay","z":"10ba0f4e1fc10011","name":"sec.","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":910,"y":440,"wires":[["20a4d6efa9b7f213"]]},{"id":"f31cc3d2467d4446","type":"debug","z":"10ba0f4e1fc10011","name":"debug 19","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1640,"y":180,"wires":[]},{"id":"01a770885c419ebf","type":"hydrawise-controller","name":"XXX","key":"XXXX-XXXX-XXXX-XXXX"},{"id":"bffecd85.30c2","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30"}]`

**Comment by RonB** [comment]
It was a bug in this release. Problem is solved in 0.0.7.beta.0
Please update the package in your palette.  It might take a while before the release is visible in node-red.
If this doesn't work please let me know and i will reopen the issue.
Good luck,
Ronald
