### ISSUE TITLE
Typo in hydrawise-controller.js

### ISSUE THREAD

**Issue by geoffreydemaagd** [RonB/node-red-contrib-hydrawise#3]
There's a typo in  hydrawise-controller.js

Line 33 
_this.contoller.zones = [];  ===>           this.controller.zones = []

With this typo node red craches

2 Jun 10:37:56 - [red] Uncaught Exception:
2 Jun 10:37:56 - [error] TypeError: Cannot set properties of undefined (setting 'zones')
    at /home/pi/.node-red/node_modules/node-red-contrib-hydrawise/hydrawise/hydrawise-controller.js:33:33
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:in

**Comment by RonB** [comment]
@geoffreydemaagd
Spotted the error. In some cases the controller is identified but the zones are not. I will fix it asap.
Thanks for the issue.

**Comment by RonB** [comment]
@geoffreydemaagd
fixed in v0.0.8 available on npm and in Nodered library
